### ISSUE TITLE
Default install location

### ISSUE THREAD

**Issue by BillSmargiassi** [kerl/kerl#129]
Why not just default to `$KERL_BASE_DIR/installs`? Why force the user to pick an install location? Keep the install directory option, but do a sane thing without specifying.

**Comment by mrallen1** [comment]
Thanks for the suggestion. I like it.  

I'm somewhat wary about changing the default tool behavior at this point in time just because the tool has been as it is for such a long time.  We would need to go through some kind of deprecation or warning cycle for *X* time whatever value of *X* seems reasonable.  

The current behavior is defined [here](https://github.com/kerl/kerl/blob/master/kerl#L882-L906) and specifies that if you set the environment variable `$KERL_DEFAULT_INSTALL_DIR` you will get the behavior you want.

If you do **not** specify an installation location, kerl will attempt to use the current directory unless it's `$HOME` (I have a PR that's being worked on #127 that modifies this code slightly to be slightly more picky about locations.)

**Comment by mrallen1** [comment]
I think we have code to do what you suggest - but please open a new ticket if you have a suggestion that isn't already covered by `KERL_DEFAULT_INSTALL_DIR` Thanks!
