### ISSUE TITLE
Typo in kerl script

### ISSUE THREAD

**Issue by mping** [kerl/kerl#167]
line https://github.com/kerl/kerl/blob/master/kerl#L1500 has an extraneous '`s`'

`list_remove "$2"s "$escaped"` should read `list_remove "$2" "$escaped"`

**Comment by mrallen1** [comment]
Thanks for the heads up!

**Comment by mguaypaq** [comment]
That `s` is definitely not extraneous! It's because the command is written `kerl delete installation ...` (with singular `installation`) whereas the installations are recorded in the file `$HOME/.kerl/otp_installations` (with plural `installations`).

Now that this change is applied, the command `kerl delete installation ...` will actually delete the installation, but not record it as deleted. As a consequence, future `kerl install ...` commands with the same target directory fail because `kerl` thinks there is already an installation there.

Please revert this commit!
