### ISSUE TITLE
Consider quoting SHML in kerl so output looks a bit nicer

### ISSUE THREAD

**Issue by jadeallenx** [kerl/kerl#186]
MIT licensed, SHML collects some VT100 escape sequences that provide terminal attributes like colors, bold, underlining, text block inversion, etc. 

https://github.com/odb/shml/blob/master/shml.sh

**Comment by fenollp** [comment]
I like this idea! What would this mean for packaging though?

Right now kerl is a single file, easily moved around and will work independent of its location.
Is the idea to merge some escape codes/emoji helpers inside the kerl script, or to add shml as a git submodule?

**Comment by sanmiguel** [comment]
I'd probably be tempted, at least for now, just to check for `shml` in the
environment, and turn on some fancier formatting if it's there. Otherwise
you're right, we'll need to merge the bits we need (or just all of it for
simplicity?) into the `kerl` script, adding maintenance burden to keep it
updated; or use a submodule and try to enforce that people put it in their
environment in an appropriate way - in which case we'd need to cope with it
being incorrectly set up anyway and may as well go with my first option...

Unless there's another way?

**Comment by mrallen1** [comment]
I was thinking we'd just inline the functions we want/need directly in kerl - no external dependencies then, sort of like how I quoted the relative/absolute path expansion shell foo previously.  We don't need every single bit of SHML - I also don't think we need to use emoji or anything - but some color output might be nice especially for success and failure conditions.
