### ISSUE TITLE
Kerl should make it easy for automation to figure out when its completed a build

### ISSUE THREAD

**Issue by jadeallenx** [kerl/kerl#187]
As I noted on commit c289a23, maybe kerl ought to touch a file when its in the middle of a build or install and then remove it when its done with that step, so that (asynchronous) automation built around kerl can know when its finished with a task.

**Comment by paulo-ferraz-oliveira** [comment]
@jadeallenx, not sure this is still relevant, as I'm not used to concurrent execution with `bash` / `kerl`. But it would have to be "safe" in the sense that if the script throws mid-way, for some other reason, a lock file might be in place which would mean manual operations to remove it (unless the goal is to force remove all locks when a specific - e.g. `build` command is run).

What points in the script do you see these locks being used/useful?

**Comment by paulo-ferraz-oliveira** [comment]
The functions for which this seems relevant are:

* `do_git_build`
* `do_normal_build`
* `do_install`
* `do_deploy`

but the `sleep` constraint mentioned by the linked commit is no longer relevant.

In any case, since this can be relevant for other use cases, I guess I can also change CI to make sure we make use of the locks thus CI'ing the implemented mechanism.

At the same time, how should `kerl` react (since I think we're not trapping exits) if a build is forcibly stopped (the lock file will remain) on a new execution? For the time being, I'll signal the occurrence and exit, but feel free to suggest other alternatives.
