### ISSUE TITLE
Erlang doesn't build correctly for certain versions of OpenSSL 1.1.x

### ISSUE THREAD

**Issue by fenollp** [kerl/kerl#226]
debian: netinstall cd image 9.1.0 
openssl: 1.1.0f-3 amd64
erlang: 18.2 compiled & installed with latest Kerl

The error: crypto app is not found.
Do we need to install openssl-dev or some other thing?

Tell me if you need more info.

**Comment by mrallen1** [comment]
Yes. I believe the library is called libssl-dev. Would you try the code on PR #222? Curious how it works out for you.

**Comment by fenollp** [comment]
@claytonfinney plz try this ^

**Comment by mpmiszczyk** [comment]
I believe you need to downgrade your `openssl`, preferably to 1.0._

I had similar problem on Arch and after a lot of googling I've managed to pinpoint the problem. As mentioned [here][http://erlang.org/pipermail/erlang-questions/2016-September/090152.html]

> Recently, new major OpenSSL version 1.1 has been released, with many
API incompatibilities, and I guess sooner or later one should port
Erlang crypto module to it. My first attempt of the porting can be
found at https://github.com/sgolovan/otp/tree/openssl11

and [here][http://erlang.2086793.n4.nabble.com/building-OTP-with-OpenSSL-1-1-0-td4718126.html]
> 2) OTP's lib/crypto/c_src/crypto.c wants "openssl/chacha.h" and "openssl/poly1305.h". which do not exist in OpenSSL 1.1.0 source. There are chacha.h and poly1305.h in crypto/include/internal, but they don't seem to be what OTP's crypto.c wants, as they don't contain required functions (like CRYPTO_chacha_20, for example)...1.0.2h, the last of OpenSSL's 1.0.x versions, simply does not have support for Chacha20/Poly1305, hence OTP compiles ok.

This issue was [solved][The crypto application now supports OpenSSL 1.1.] in Erlang itself and 20.+ will compile without any problems.  But all distributions (and I would guess any operating systems) with OpenSSL 1.1+ will cause issues while building older Erlangs (even 19.3). If you look closely into logs you will find that make is able to find OpenSSL but to to use it 
```
checking for OpenSSL >= 0.9.7 in standard locations... found; but not usable
configure: WARNING: No (usable) OpenSSL found, skipping ssl, ssh and crypto applications
```

Arch linux it

**Comment by mrallen1** [comment]
Thanks for the information!
