### ISSUE TITLE
Kerl silently creates a build without crypto when no libssl headers are availible

### ISSUE THREAD

**Issue by kanes115** [kerl/kerl#237]
Kerl still does not ask a user if he really wants a build without crypto included (when he lacks libssl headers). Such a build is pretty useless as e.g. rebar3 won't work without crypto.app. That would be great to give a warning in such situation.

I came across this problem on Ubuntu 16.04.

**Comment by mrallen1** [comment]
We have been outputting the configure analysis of build options since July 2016 which pretty clearly shows whether crypto will be built or not.  We also have a pending PR #221 to check Linux systems for required libraries/packages before a build starts.

What sort of warning do you think would be suitable? What additional information would you like kerl to warn you about?

**Comment by mrallen1** [comment]
Also curious if you're running into this [issue][1]

[1]: https://github.com/kerl/kerl/issues/226#issuecomment-327915702

**Comment by mrallen1** [comment]
I think we've addressed this issue about as well we can, so I'm going to close this issue. Please open a new issue if you're still having trouble. Thanks.
