### ISSUE TITLE
More Specific OTP Releases by Including Patch Version

### ISSUE THREAD

**Issue by HangingClowns** [kerl/kerl#240]
When I look at current releases, I just see 20.1, but I'm not sure of the patch release. Can we somehow include the patch? As you can see 20.1.4 came out, recently, and I'm not sure what patch release I'm on:

http://erlang.org/pipermail/erlang-questions/2017-November/094085.html

**Comment by sanmiguel** [comment]
Hi there, we now have the option to change the "build backend", which changes where we pull releases from.

If you add `export KERL_BUILD_BACKEND=git` to your env or your `~/.kerlrc`, this will tell kerl to use the git tags directly, instead of the official release numbers from Erlang.org, which never include patch releases.

You will need to run `kerl update releases` after setting this to pick up the updated list. After that you'll be able to build and install patch releases as you normally would any other.

I'll close this for now but please feel free to reopen if you have more questions or if anything is unclear.

Cheers!
