### ISSUE TITLE
How to set a global version

### ISSUE THREAD

**Issue by saileifeng** [kerl/kerl#256]

**Comment by fenollp** [comment]
A version of what? Can you describe a use case?

**Comment by mrallen1** [comment]
I think the suggestion is pointing toward other installation management tools like [rbenv][1] or [plenv][2] which allow you to configure a universal global and per-project "local" version of ruby or perl.

So the use case would be something like, "I usually want to develop using OTP 20.2, but I have this project which can only run on OTP 17 because reasons.  So I want to make sure that when I'm in the old project directory, kerl knows that it should activate OTP 17."

[1]: https://github.com/rbenv/rbenv#command-reference
[2]: https://github.com/tokuhirom/plenv#command-reference

**Comment by Spring-Plum** [comment]
yes,my question is mrallen1 said

**Comment by Spring-Plum** [comment]
Yes, my question is the same as mrallen1.

**Comment by rjcoelho** [comment]
I use autoenv (or direnv), to eval scripts (kerl activate) on directory entry.

**Comment by mrallen1** [comment]
Right now, that's probably the best solution.  I'd be interested in a PR which implements this functionality but I'm not interested in developing it myself.

**Comment by rjcoelho** [comment]
I use kerl to activate per-user (home) or per-project erlang version, not global/system-wide erlang version because other packages (rebar,...) may depend on it. For system erlang i use system package manager (yum, brew, ...).

Per-user is set on ~/.{bash,zh}rc, per-project is set on projects root .envrc (by using autoenv or similar and keeping .envrc under source control) and global is set on /etc/{bash,zh}rc.

**Comment by sanmiguel** [comment]
Similarly I've been using asdf lately to manage some Erlang versions but I
was thinking about writing a plugin for asdf that uses kerl to
build/install. If others are interested too I might get to it sooner...

**Comment by mrallen1** [comment]
OK, I'm going to mark this issue at "help wanted" and leave it open for a while. Maybe someone will jump on it and work it.

**Comment by fenollp** [comment]
How about reading the `minimum_otp_version` key of rebar.config and activating the highest installed version that matches this pattern?
erlang.mk maybe has a similar setting?
Maybe better yet would be to have a way to ask either tools for this pattern so that rebar3 providers would be supported?

**Comment by mrallen1** [comment]
The less we rely on rebar for behavior signals the better IMO. The way other tools handle this situation is with a dot file in a directory like `.kerl-erlang-version` and the contents of that file points to some installation name as stored in `~/.kerl/otp_installations`

Honestly, I am not convinced this is functionality kerl should take on itself. Seems like some other tool could be integrated with kerl to work in the desired way.

**Comment by paulo-ferraz-oliveira** [comment]
Is there still interest in implementing this? I'm used to having the global version in e.g. my shell's rc. Maybe it's not ideal, but it works, though with `asdf` there's now a better mechanism to fetch a specific version per folder (I was also using `direnv` in the past). And I agree that it's probably to specific a problem (which e.g. `asdf` addresses already to be included in the tool - `kerl`).

**Comment by jadeallenx** [comment]
Closing, thanks - I think using asdf for this purpose is fine tbh
