### ISSUE TITLE
Checking Xcode version logs a warning if it doesn't exist

### ISSUE THREAD

**Issue by mkarnebeek** [kerl/kerl#343]
See https://github.com/kerl/kerl/blob/cd6280cb7de71e0d3c3c61648aeca12e2b70cffb/kerl#L661. It logs:

```
/Users/[..]/.asdf/plugins/erlang/kerl: line 661: /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild: No such file or directory
```

There is a thread on the asdf plugin about it at https://github.com/asdf-vm/asdf-erlang/issues/151

**Comment by sascha-wolf** [comment]
From what I can gather `kerl` only uses `xcodebuild` to determine whether or not it needs to apply certain MacOS Catalina only patches.

Since I don't use Catalina (yet) and don't plan on installing Xcode I've removed the following lines from my local `kerl` installation which does the trick.

https://github.com/kerl/kerl/blob/cd6280cb7de71e0d3c3c61648aeca12e2b70cffb/kerl#L661

and 

https://github.com/kerl/kerl/blob/cd6280cb7de71e0d3c3c61648aeca12e2b70cffb/kerl#L661
