### ISSUE TITLE
How to use kerl on machine that doesn't have internet connection?

### ISSUE THREAD

**Issue by h9812** [kerl/kerl#391]
I'm going to use kerl on machine that doesn't have internet connection. How can I specify kerl to use local tarballs instead of downloading from internet?

**Comment by jadeallenx** [comment]
There is currently no convenient way to tell kerl to use tarballs and other release metadata from a local resource/disconnected from the internet.

It is probably possible to add that feature but it doesn’t exist in the current release.

Sent from my iPhone

On Dec 13, 2021, at 2:31 AM, Tran Minh Hieu ***@***.***> wrote:

﻿

I'm going to use kerl on machine that doesn't have internet connection. How can I specify kerl to use local tarballs instead of downloading from internet?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkerl%2Fkerl%2Fissues%2F391&data=04%7C01%7C%7C79247816a2a14a73a2f008d9be12f33e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749810861875795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OMGa6cP4dnPbBrKhDc%2B1QFx1Db9WwbaE5WLY%2BsNsk0I%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAABR7OGHFKHCAAG46MD6WULUQWVNZANCNFSM5J5QHBJA&data=04%7C01%7C%7C79247816a2a14a73a2f008d9be12f33e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749810861875795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mPtxPeSQJk32EgjtAa3ZJ5O8XtwKYqO8U3skxsFirbs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C79247816a2a14a73a2f008d9be12f33e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749810861875795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VSwyT9k1A%2B8bMtbciSAuqFCB4BxaJXipw9pAiGjg4ls%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C79247816a2a14a73a2f008d9be12f33e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749810861875795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4GHBZWEtpzzmbcvBBDjyIQ%2F%2FbZ3B1viReCUWiwHkjrQ%3D&reserved=0>.
