### ISSUE TITLE
'kerl deploy' not working

### ISSUE THREAD

**Issue by jimdigriz** [kerl/kerl#468]
#### The bug

```
alex@hanzawa:~/src/kerl$ kerl deploy sarasti.local /home/alex/src/kerl/install/26
Couldn't ssh to sarasti.local
```

Using `strace` the problem is:
```
[pid 1186991] execve("/usr/bin/ssh", ["ssh", "", "sarasti.local", "true"], 0x5559e2a57be8 /* 43 vars */) = 0
```

Looking into the script the problem is that `$KERL_DEPLOY_SSH_OPTIONS` is double quoted which passes through.
```
if ! ssh "$KERL_DEPLOY_SSH_OPTIONS" "$host" true >/dev/null 2>&1; then
    l=e stderr "Couldn't ssh to $host"
    exit 1
fi  
```

Similarly for the `rsync` part:
```
if ! rsync -aqz -e "ssh $KERL_DEPLOY_SSH_OPTIONS" "$KERL_DEPLOY_RSYNC_OPTIONS" "$path/" "$host:$remotepath/"; then
    l=e stderr "Couldn't rsync Erlang/OTP $rel ($path) to $host ($remotepath)"
    exit 1
fi
```

Seeing this, we can work around this by using NOP values, the following works:
```
KERL_DEPLOY_SSH_OPTIONS='-6' KERL_DEPLOY_RSYNC_OPTIONS='-e ssh' kerl deploy sarasti.local ~/src/kerl/install/26
```

I would suggest dropping the double quotes as if the user provides multiple options it is going to break, but if they really are needed you probably can use instead:

```
${KERL_DEPLOY_SSH_OPTIONS:+"$KERL_DEPLOY_SSH_OPTIONS"}
```

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Operating System: Debian 'bookworm' 12
* `kerl`: tip of `main`: `46ea061d4ce7db2ed1de3099ac0a36e31744fac4`

#### How to replicate

An ordered list of steps to replicate the bug, e.g.:

1. run `kerl deploy ...`

#### Expected behaviour

SSH/RSYNC over the OTP goodness.

#### Additional context

Any other context about the bug.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for reporting this, @jimdigriz. I'll fix it soon.

**Comment by paulo-ferraz-oliveira** [comment]
This issue was introduced by me [here](https://github.com/kerl/kerl/pull/463/files#diff-2df8b125dc6a121ab2da71f2e0fe968fd2d8d710fbecfcb53e93fc2c6c05850bL1755). I was sure to have review and reverted changes to ShellCheck stuff, but some I missed.

1. I'll look at that pull request closely again
2. I'll revert changes that might causes issues like this (I guess for those specific cases, the lack of a comment next to the directive lead me to believe, wrongly, this was just a "getting it out of the way" type of situation)
3. these paths are not tested, and I'm not sure they'd easily be
