### ISSUE TITLE
FTB docs

### ISSUE THREAD

**Issue by JiffB** [kerl/kerl#517]
#### Ze bug

Hi,
I followed the git mod'op and 25.3.2.10 built like charm, however : 
```
KERL_BUILD_DOCS=yes kerl build 25.3-builtdocs
failed with : 
ERROR: '25.3_builtdocs' is not a valid Erlang/OTP release
```
I also tried replacing `25.3` with `25.3.2.10` but got the same answer.

NB: At this stage, I did not already installed this kerl compilation (that will go into /usr/local/erlang/25.3 when the docs problem will be solved).

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Operating System: Debian bullseye on a NanoPC-T6 (aarch64 - CPU: RK3588)
* Erlang/OTP: None installed
* `kerl`: Git master version

#### How to replicate

An ordered list of steps to replicate the bug, e.g.:

1. run `kerl build 25.3`
2. run `KERL_BUILD_DOCS=yes kerl build 25.3-builtdocs`
3. got `ERROR: '25.3-builtdocs' is not a valid Erlang/OTP release.`

#### Expected behaviour

Erlang docs to build as easily as Erlang executables

#### Additional context

An old tarball compilation (25.3.2.5) was manually removed as there's no uninstall in its Makefile (man pages not removed, no time for that) before using kerl.

**Comment by paulo-ferraz-oliveira** [comment]
Hi.

```
KERL_BUILD_DOCS=yes kerl build 25.3-builtdocs
failed with : 
ERROR: '25.3_builtdocs' is not a valid Erlang/OTP release
```

mentions `25.3-builtdocs` in the input, but `25.3_builtdocs` in the output. I'm unaware of any such replace we'd do.

You can list your local builds with `kerl list builds`.
You can list your local installations with `kerl list installations`.

It's possible there's a collision somewhere.

---

In any case, `kerl` does not attempt any magic on the input (meaning `builtdocs` is not a special string for it, for example) when you try to build docs, and it seems that using `kerl build 25.3-builtdocs` should fail, because:

1. `kerl list releases` does not include that release `25.3-builtdocs` (what Git repo are you getting it from?)
2. `kerl build` states `usage: /opt/homebrew/bin/kerl build <release> [build_name]` which means you need to use a version listed in the previous command's output (unless I'm missing some of your shell's context and you're setting `kerl` variables that would change its behavior).

---

`KERL_BUILD_DOCS=yes kerl build 25.3` should build 25.3 locally with docs, in any case, if you wanna try that one out.

**Comment by JiffB** [comment]
On Fri, 31 May 2024 08:07:36 -0700
"Paulo F. Oliveira" ***@***.***> wrote:

Hi,

> […]
> 
> `KERL_BUILD_DOCS=yes kerl build 25.3` should build 25.3 locally with
> docs, in any case, if you wanna try that one out.

It works, thanks and sorry for the noise.

Jean-Yves

**Comment by paulo-ferraz-oliveira** [comment]
No prob. Glad we could help.
