### ISSUE TITLE
also pull in rebar?

### ISSUE THREAD

**Issue by nicferrier** [kerl/kerl#81]
I find it a little annoying that I have to pull in rebar separately. 

If I build an erlang would it not be useful to mix in rebar?

**Comment by mrallen1** [comment]
Not everyone uses rebar and it's not too difficult to stash rebar or rebar3 in `$HOME/bin` or some `/usr/local/bin` or something like that.  It sounds like in forthcoming OTP releases, rebar3 will be bundled with Erlang releases.

**Comment by mrallen1** [comment]
On reflection, we shouldn't make any assumptions about the build tools people use to compile Erlang applications/projects. I appreciate the thought, but I'm going to close this issue.

**Comment by fenollp** [comment]
Rebar3 is now supposed to be the official tool and is not yet packaged with OTP. Moreover it is meant to support the last 3 major versions meaning OTP releases that can be built with kerl will not be able to use a drop-in version of rebar3 that works / is compiled for the activated version. 
So I’m thinking let’s either push for the folks over at rebar3.org to host a rebar3 “binary” compiled for each OTP release for easy installation;
Or support a config option to pull in and compile rebar3 at the last working version for a given OTP release. If/When OTP comes with rebar3 then kerl wouldn’t build it. 

One step further may be to check which version of rebar3 is already installed and activate kerl’s iff that is not compatible. 

What do you guys think?

**Comment by paulo-ferraz-oliveira** [comment]
@fenollp, you can pull a pre-compiled version from the GitHub releases (e.g. here's [3.8.0](https://github.com/erlang/rebar3/releases/tag/3.8.0)), if that seems to be what you're looking for. I personally have `rebar3` "detached" from the `kerl` installation, but can see value in somebody just wanting to `activate` and have the whole system ready to go.

On the other hand, if you tie a `kerl` version to a `rebar3` version it's possible you'll need a command to update it, since the `OTP` and `rebar3` release cycles aren't sync.'ed and it's common to have rebar3 releases that improve behaviour or fix bugs.

**Comment by fenollp** [comment]
I agree with you (and Mark). If the OTP team doesn't judge that rebar3 should be part of an OTP installation who am I to say otherwise anyway :)
